### ISSUE TITLE
demo bug

### ISSUE THREAD

**Issue by Dogtiti** [wellyshen/react-cool-inview#720]
![image](https://user-images.githubusercontent.com/38354472/149501249-f4e088d5-cc39-475a-a70f-43b3abf42a75.png)

**Comment by max-sym** [comment]
@Dogtiti thanks for reporting.
What was your browser, OS and what did you do to achieve this?

**Comment by Dogtiti** [comment]
@max-sym  Chrome 98.0.4758.102
I don't know what did I do ,I just play the demo in normal ways ,and then it shows as above

**Comment by max-sym** [comment]
Catched it!
<img width="863" alt="Screenshot 2022-02-15 at 9 00 31 AM" src="https://user-images.githubusercontent.com/32452032/154027988-58a5e3d5-5f7e-4a73-b536-51c4e44a749e.png">

Steps to reproduce: just scroll randomly and fast.
OS: MacOS
Browser:Chrome

**Comment by heitorado** [comment]
Hi there! @max-sym, I was trying to build an infinite scroll that updates the page number as the user scrolls (pretty much like the emojis upload in the demo website, just use numbers instead). I believe that the bug I found might be related to this one.

https://user-images.githubusercontent.com/24229855/160012735-3a1ead67-87b8-445f-963c-f13ca5c678c1.mov

It happens if as soon as you "arrive" in an element (i.e. the emoji updates), scroll in the opposite direction. It will not trigger the callbacks for the element immediately before the one you arrived (I believe it should, since you are now "going back"). This makes the pagination go crazy and skip pages if the scroll happen in this pattern.

> Steps to reproduce (in demo): Scroll down slowly. As soon as the new emoji appears in the text above the box, scroll in the opposite direction. It will not update back to the previous emoji.
> OS: MacOS
> Browser: Brave

Do you have any clues of what may be causing this? I'd be happy to help if possible. Just need some starting point to start investigating.

Thanks for the amazing work, also. Great package.
Cheers.

**Comment by wellyshen** [comment]
Thank you. I can reproduce the bug.

**Comment by SaidMarar** [comment]
The problem is because the display area (**root**) takes the viewport as default value in the Intersection observer and also the **margin** style affect the synchronization beween slides.
Now you can notice when both slides reach the half height of slider, their intersection is triggered.
I made the fix above check it guys ;)
